version: "3.8"
services:
    thuyitss:
        container_name: thuyitss
        volumes:
            -   ./:/app
        ports:
            - "7777:7777"
        image: node:slim
        command: bash -c "cd /app && npm install && npm run start"

networks:
    be-network:
        driver: bridge

volumes:
    be-database:
        driver: local
